{% set version = "1.2.16" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fdrtool
  version: {{ version|replace("-", "_") }}

source:
  fn: fdrtool_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/fdrtool_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fdrtool/fdrtool_{{ version }}.tar.gz
  sha256: e7dea648ee018e2c8c8834084051c76f7e8b2b42067772c62035a941c32457a9

build:
  merge_build_host: true  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('fdrtool')"           # [not win]
    - "\"%R%\" -e \"library('fdrtool')\""  # [win]

about:
  home: http://strimmerlab.org/software/fdrtool/
  license: GPL (>= 3)
  summary: Estimates both tail area-based false  discovery rates (Fdr) as well as local false discovery rates (fdr) for a  variety of null models (p-values, z-scores, correlation coefficients, t-scores).  The proportion of null values and the parameters of the null  distribution are adaptively estimated from the data.  In
    addition, the package  contains functions for non-parametric density estimation (Grenander estimator),  for monotone regression (isotonic regression and antitonic regression with weights), for computing the greatest convex minorant (GCM) and the least concave majorant (LCM),  for the half-normal and correlation distributions,
    and for computing empirical higher criticism (HC) scores and the corresponding decision threshold.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
