travis:
  secure:
    BINSTAR_TOKEN: YaL3H8TvDHGeSAsJbF+TD3YFh48iLFf2KpPiNVnzX2dX49sBXcmE65I1TTVeLn7O7VrZbrxZVd8h6N5oGKPjTDtDJaGh3LEG83KlJmCYzwmCClViybo2t8MhbA7CZW5CYV1PigxpVoQ0t88Z2tumI1xFERSuND60a3ksUfR3ZAd81O4t2GkJ26NyZZ9aKpF/XjQsnp254KVDTwHuBsiakGqJDxcqG/8n+R7b4YStlS1Mb3emdNi0386yQ1LvOKm4xgNqKtLv+74JJ+rONKqAbYfTK8rL819wEK6HHEhX0wV75PI9gnTQUQ0PONEHr188yZIEOScy5grNTh3Bny7XJ4dSksNCNEzqfanQoOTug9T+z7ElQpM1JV4j4eosXB1oGPZM91pQu8bw0wrlaHZ2k3Go+o5Ww2aMszliDndbeRDW7g0WLdqzzAvPZGZmt4XT8fZxqUwQsflNq4a+rcR/wIMXFvGK64L9Lwg/uEIFYfcbgegSUPQ2HVgmDW7KNjYaL2fTnHd4eicBFX38HthcUiz0jlyU6b1tMvbJ1QCr4RisRiWR3kJXUfpBVF9/2Ploutv/YAHuqr3+K/HELopEQ6mM7E+F40JirEvmO4GEFbnHH/s3aPM0QBW98HagjTktG96au8HXR3doW3YhNFNRdCnKkgrpamHSj+8HKC6bNIw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
