appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: XY5PijE02foWZkbWCt88K/JkBEFM6w1ROr7VTjK4v2CQHs9xthOH+2WEaKuPLqx/gOMBeKZwBmSBbVbdQK1K5hGjL94wbCYaG/HkBPmjHST2Ct1zC4fzNVLmx/lVLO3cvPLZzFlzXIex8Z7z1lkrZ/a5wPF8YcP/BGNckMyHelJEBSrnIFBeKm3JXpY0sXKHfm0yUKxI1qbnuQDsnXZ3IgMRIh+vS/FPpM9qJsG5nkOnbKhjiiLokAut157x6dw6mjPQ3m4Ibw11ut5B6eC/5xyx5yzA3Mc4yP85E4TF4+JwXJzolEujspiekq3UIsGW//9/kvVtKuX9rLngiryFrmJ5uWpbLMDnOsdHH2MG/KNqYEG8PZaY7nAG2UkjVWtepPjVy8ghQNJ+D7q2Cj6zZtv0ZzPqjg2IgTGPyPycDgrV4xGoKB+YJjIDl/OOOGqr2Q8NpImsNA6kc3lWlSmmuM2FGYwakBrbrlbP1ASkhxxHQDwu62Mo+G2u2V6lM8BR+kFbO04I1b0F+sM8zwZizcagL6zxRfHdLoUEgGFuQSlQY5BRnXLP4oOHfDG5ksmZuQNTNxqPKWBuy/R82lVpo+p9iLmJq624dEHTc7eMHafKCB050+goqDyMk5RddxpHMFE6DLFGkFQNDOCeCgqE3RCd9iiU2d91IJJMQsr6TrU=
